;;; gnus-inbox-test.el --- Tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'gnus-inbox)
(defvar gnus-number)

(ert-deftest gnus-inbox-summary-keys-use-inbox-dispositions ()
  (gnus-inbox-enable)
  (dolist (binding '(("a" . gnus-inbox-archive)
                     ("d" . gnus-inbox-delete)
                     ("k" . gnus-inbox-delete)
                     ("l" . gnus-inbox-read-later)
                     ("!" . gnus-summary-tick-article-forward)
                     ("u" . gnus-inbox-restore)))
    (should (eq (lookup-key gnus-summary-mode-map (kbd (car binding)))
                (cdr binding)))))

(ert-deftest gnus-inbox-dispositions-are-exclusive-and-independent ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "example")
        (gnus-newsgroup-archived nil)
        (gnus-newsgroup-trashed nil))
    (cl-letf (((symbol-function 'gnus-get-info)
               (lambda (_group) info)))
      (gnus-inbox--set-mark '("example" . 12) 'archive t)
      (should (gnus-inbox--marked-p '("example" . 12) 'archive))
      (should-not (gnus-inbox--marked-p '("example" . 12) 'trash))
      (should (equal gnus-newsgroup-archived '(12)))
      (should-not (gnus-info-read info))
      (gnus-inbox--disposition '("example" . 12) 'read-later)
      (should (gnus-inbox--marked-p '("example" . 12) 'read-later))
      (should-not (gnus-inbox--marked-p '("example" . 12) 'archive))
      (gnus-inbox--disposition '("example" . 12) 'trash)
      (should-not (gnus-inbox--marked-p '("example" . 12) 'archive))
      (should-not (gnus-inbox--marked-p '("example" . 12) 'read-later))
      (should (gnus-inbox--marked-p '("example" . 12) 'trash))
      (should-not (gnus-info-read info)))))

(ert-deftest gnus-inbox-virtual-source-resolves-to-original ()
  (let ((gnus-newsgroup-name "nnvirtual:subscriptions"))
    (cl-letf (((symbol-function 'gnus-nnselect-group-p) (lambda (_) nil))
              ((symbol-function 'gnus-virtual-group-p) (lambda (_) t))
              ((symbol-function 'gnus-group-real-name) (lambda (_) "subscriptions"))
              ((symbol-function 'nnvirtual-find-group-art)
               (lambda (_group _article) '("nndouban:group.174786" . 456))))
      (should (equal (gnus-inbox--source 99)
                     '("nndouban:group.174786" . 456))))))

(ert-deftest gnus-inbox-archive-requires-a-cached-copy ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "example"))
    (cl-letf (((symbol-function 'gnus-get-info) (lambda (_) info))
              ((symbol-function 'gnus-inbox--source)
               (lambda (_) '("example" . 12)))
              ((symbol-function 'gnus-cache-file-name)
               (lambda (&rest _) "/nonexistent/gnus-archive-test"))
              ((symbol-function 'gnus-cache-possibly-enter-article)
               (lambda (&rest _) nil)))
      (should-error (gnus-inbox-archive 12) :type 'user-error)
      (should-not (gnus-inbox--marked-p '("example" . 12)
                                                       'archive)))))

(ert-deftest gnus-inbox-archive-records-source-after-caching ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "nnvirtual:subscriptions")
        (file (make-temp-file "gnus-archive-test-")))
    (unwind-protect
        (progn
          (delete-file file)
          (cl-letf (((symbol-function 'gnus-get-info) (lambda (_) info))
                    ((symbol-function 'gnus-inbox--source)
                     (lambda (_) '("example" . 12)))
                    ((symbol-function 'gnus-cache-file-name)
                     (lambda (&rest _) file))
                    ((symbol-function 'gnus-cache-possibly-enter-article)
                     (lambda (&rest _) (with-temp-file file (insert "cached")))))
            (gnus-inbox-archive 99)
            (should (gnus-inbox--marked-p '("example" . 12)
                                                          'archive))
            (should-not (gnus-inbox--marked-p '("example" . 12)
                                                              'trash))))
      (when (file-exists-p file) (delete-file file)))))

(ert-deftest gnus-inbox-inbox-hides-all-three-dispositions ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "example")
        (gnus-number 12))
    (cl-letf (((symbol-function 'gnus-get-info) (lambda (_) info))
              ((symbol-function 'gnus-inbox--source)
               (lambda (_) '("example" . 12))))
      (should (gnus-inbox-visible-p))
      (dolist (mark '(read-later archive trash))
        (gnus-inbox--disposition '("example" . 12) mark)
        (should-not (gnus-inbox-visible-p))))))

;;; gnus-inbox-test.el ends here
