;;; gnus-inbox-test.el --- Tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'gnus-inbox)
(defvar gnus-number)

(ert-deftest gnus-inbox-summary-keys-use-inbox-dispositions ()
  (gnus-inbox-enable)
  (dolist (binding '(("a" . gnus-inbox-archive)
                     ("d" . gnus-inbox-delete)
                     ("k" . gnus-inbox-delete)
                     ("l" . gnus-inbox-read-later)
                     ("!" . gnus-summary-tick-article-forward)
                     ("u" . gnus-inbox-restore)))
    (should (eq (lookup-key gnus-summary-mode-map (kbd (car binding)))
                (cdr binding)))))

(ert-deftest gnus-inbox-dispositions-are-exclusive-and-independent ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "example")
        (gnus-newsgroup-archived nil)
        (gnus-newsgroup-trashed nil))
    (cl-letf (((symbol-function 'gnus-get-info)
               (lambda (_group) info)))
      (gnus-inbox--set-mark '("example" . 12) 'archive t)
      (should (gnus-inbox--marked-p '("example" . 12) 'archive))
      (should-not (gnus-inbox--marked-p '("example" . 12) 'trash))
      (should (equal gnus-newsgroup-archived '(12)))
      (should-not (gnus-info-read info))
      (gnus-inbox--disposition '("example" . 12) 'read-later)
      (should (gnus-inbox--marked-p '("example" . 12) 'read-later))
      (should-not (gnus-inbox--marked-p '("example" . 12) 'archive))
      (gnus-inbox--disposition '("example" . 12) 'trash)
      (should-not (gnus-inbox--marked-p '("example" . 12) 'archive))
      (should-not (gnus-inbox--marked-p '("example" . 12) 'read-later))
      (should (gnus-inbox--marked-p '("example" . 12) 'trash))
      (should-not (gnus-info-read info)))))

(ert-deftest gnus-inbox-virtual-source-resolves-to-original ()
  (let ((gnus-newsgroup-name "nnvirtual:subscriptions"))
    (cl-letf (((symbol-function 'gnus-nnselect-group-p) (lambda (_) nil))
              ((symbol-function 'gnus-virtual-group-p) (lambda (_) t))
              ((symbol-function 'gnus-group-real-name) (lambda (_) "subscriptions"))
              ((symbol-function 'nnvirtual-find-group-art)
               (lambda (_group _article) '("nndouban:group.174786" . 456))))
      (should (equal (gnus-inbox--source 99)
                     '("nndouban:group.174786" . 456))))))

(ert-deftest gnus-inbox-archive-requires-a-cached-copy ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "example"))
    (cl-letf (((symbol-function 'gnus-get-info) (lambda (_) info))
              ((symbol-function 'gnus-inbox--source)
               (lambda (_) '("example" . 12)))
              ((symbol-function 'gnus-cache-file-name)
               (lambda (&rest _) "/nonexistent/gnus-archive-test"))
              ((symbol-function 'gnus-cache-possibly-enter-article)
               (lambda (&rest _) nil)))
      (should-error (gnus-inbox-archive 12) :type 'user-error)
      (should-not (gnus-inbox--marked-p '("example" . 12)
                                                       'archive)))))

(ert-deftest gnus-inbox-archive-records-source-after-caching ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "nnvirtual:subscriptions")
        (file (make-temp-file "gnus-archive-test-")))
    (unwind-protect
        (progn
          (delete-file file)
          (cl-letf (((symbol-function 'gnus-get-info) (lambda (_) info))
                    ((symbol-function 'gnus-virtual-group-p) (lambda (_) nil))
                    ((symbol-function 'gnus-inbox--source)
                     (lambda (_) '("example" . 12)))
                    ((symbol-function 'gnus-cache-file-name)
                     (lambda (&rest _) file))
                    ((symbol-function 'gnus-cache-possibly-enter-article)
                     (lambda (&rest _) (with-temp-file file (insert "cached")))))
            (gnus-inbox-archive 99)
            (should (gnus-inbox--marked-p '("example" . 12)
                                                          'archive))
            (should-not (gnus-inbox--marked-p '("example" . 12)
                                                              'trash))))
      (when (file-exists-p file) (delete-file file)))))

(ert-deftest gnus-inbox-inbox-hides-all-three-dispositions ()
  (let ((info (gnus-info-make "example" 2 nil nil))
        (gnus-newsgroup-name "example")
        (gnus-number 12))
    (cl-letf (((symbol-function 'gnus-get-info) (lambda (_) info))
              ((symbol-function 'gnus-inbox--source)
               (lambda (_) '("example" . 12))))
      (should (gnus-inbox-visible-p))
      (dolist (mark '(read-later archive trash))
        (gnus-inbox--disposition '("example" . 12) mark)
        (should-not (gnus-inbox-visible-p))))))

(ert-deftest gnus-inbox-virtual-dispositions-survive-native-summary-save ()
  (require 'nnvirtual)
  (let* ((source (gnus-info-make "example" 2 nil nil))
         (virtual (gnus-info-make "nnvirtual:timeline" 2 nil nil))
         (gnus-newsrc-hashtb (make-hash-table :test #'equal))
         (nnvirtual-current-group "timeline")
         (nnvirtual-component-groups '("example"))
         (nnvirtual-mapping-offsets [("example" . 0)])
         (nnvirtual-mapping-table (list [20 0 1 21 0])))
    ;; Native-compiled Gnus inlines gnus-get-info; populate its real table.
    (puthash "example" (list "example" source) gnus-newsrc-hashtb)
    (puthash "nnvirtual:timeline" (list "nnvirtual:timeline" virtual) gnus-newsrc-hashtb)
    (with-temp-buffer
      (setq-local gnus-newsgroup-name "nnvirtual:timeline")
      (setq-local gnus-newsgroup-unseen nil)
      (dolist (entry gnus-article-mark-lists)
        (set (make-local-variable
              (intern (format "gnus-newsgroup-%s" (car entry)))) nil))
      (cl-letf (((symbol-function 'gnus-get-info)
                 (lambda (group) (if (equal group "example") source virtual)))
                ((symbol-function 'gnus-virtual-group-p)
                 (lambda (group) (equal group "nnvirtual:timeline")))
                ((symbol-function 'gnus-check-backend-function) (lambda (&rest _) nil)))
        (dolist (mark '(trash read-later archive))
          (gnus-inbox--disposition '("example" . 12) mark)
          (gnus-update-marks)
          ;; This is the real nnvirtual save path, which clears component
          ;; marks and replaces them with the virtual group's snapshot.
          (nnvirtual-update-read-and-marked nil nil)
          (should (gnus-inbox--marked-p '("example" . 12) mark))
          (should (gnus-inbox--marked-p '("nnvirtual:timeline" . 13) mark)))
        (gnus-inbox--disposition '("example" . 12) nil)
        (gnus-update-marks)
        (nnvirtual-update-read-and-marked nil nil)
        (should-not (gnus-inbox--marked-p '("example" . 12) 'archive))))))

(defun gnus-inbox-test--viewport (deleted point-line top-line)
  "Filter DELETED from a time-sorted Summary and return its viewport."
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (let ((gnus-newsgroup-display #'ignore)
            (order '(90 4 71 8 63 12 55 16 47 20 39 24)))
        (cl-labels ((render (numbers)
                      (erase-buffer)
                      (dolist (number numbers)
                        (insert (propertize (format "  [0: Author] Subject %d\n" number)
                                            'gnus-number number)))))
          (render order)
          (goto-char (point-min))
          (forward-line top-line)
          (set-window-start (selected-window) (point) t)
          (forward-line (- point-line top-line))
          (cl-letf (((symbol-function 'gnus-summary-limit-to-display-predicate)
                     (lambda ()
                       (render (cl-set-difference order deleted))
                       ;; Simulate Gnus choosing a distant successor
                       ;; and losing window-start while regenerating Summary.
                       (goto-char (point-max))
                       (forward-line -1)
                       (set-window-start (selected-window) (point-min) t))))
            (gnus-inbox--refresh-inbox))
          (list (gnus-summary-article-number)
                (save-excursion
                  (goto-char (window-start (selected-window)))
                  (gnus-summary-article-number))))))))

(ert-deftest gnus-inbox-filter-keeps-visible-successor-and-top ()
  (should (equal (gnus-inbox-test--viewport '(63) 4 2) '(12 71))))

(ert-deftest gnus-inbox-filter-replaces-deleted-top-with-successor ()
  (should (equal (gnus-inbox-test--viewport '(71) 2 2) '(8 8))))

(ert-deftest gnus-inbox-filter-last-article-selects-visible-predecessor ()
  (should (equal (gnus-inbox-test--viewport '(24) 11 2) '(39 71))))

;;; gnus-inbox-test.el ends here
